--- # Connection
#ansible-playbook user.yaml
# link
- name: Install packages
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  # -name: Print all available facts
  # ansible.builtin.debug:
  #   var: ansible_facts


  - name: Print os_family
    ansible.builtin.debug:
      var: ansible_facts['os_family']


  - name: Print distribution
    ansible.builtin.debug:
      var: ansible_facts['distribution']

   - name: Print distribution_version
    ansible.builtin.debug:
      var: ansible_facts['distribution_version']

    debug:
      msg: "{{ansible_facts}}"












  # Task block
  - name: Install telnet 
    ansible.builtin.package:
      name: telnet
      state: absent            #present       #latest
